#!/bin/sh
# scripts/lib/installer/audio.sh
# ALSA "default" auto-configuration for boards whose only audio output does not
# enumerate as card 0.
#
# ALSA's stock "default" PCM resolves to hw:0. On several supported boards there
# is no card 0 — the only outputs are HDMI audio codecs that enumerate at higher
# indices. The classic case is a Raspberry Pi (incl. CM4) driving a BTT HDMI5 (or
# similar) screen whose built-in speaker rides HDMI audio: the only cards are
# vc4hdmi0/vc4hdmi1 at indices 1/2, so "default" → hw:0 fails with
# "snd_pcm_dmix_open: unable to open slave" and UI sound is dead.
#
# Fix: write /etc/asound.conf remapping "default" onto the detected output. This
# is the standard ALSA mechanism and fixes everything that opens "default" —
# HelixScreen, aplay, speaker-test — not just our app. We never touch the user's
# helixscreen.env (that file is reserved for user/runtime overrides), and we never
# clobber an existing /etc/asound.conf.
#
# When more than one HDMI codec is present we pick the one whose sink is actually
# connected, read from the codec's ELD (monitor_present / eld_valid in
# /proc/asound/cardN/eld*), so a screen on the second HDMI port is selected over
# an idle first port automatically.
#
# Reads: ASOUND_PROC_DIR (default /proc/asound), ASOUND_CONF (default
#        /etc/asound.conf), SUDO
# Writes: ASOUND_CONF (only when absent and a remap is needed)

# Source guard
[ -n "${_HELIX_AUDIO_SOURCED:-}" ] && return 0
_HELIX_AUDIO_SOURCED=1

# Injectable for tests; default to the real kernel/system paths.
ASOUND_PROC_DIR="${ASOUND_PROC_DIR:-/proc/asound}"
ASOUND_CONF="${ASOUND_CONF:-/etc/asound.conf}"

# Does an HDMI codec report a connected sink with valid audio?
# $1 = card directory under ASOUND_PROC_DIR. Returns 0 if connected.
_alsa_card_sink_connected() {
    _card_dir="$1"
    for _eld in "$_card_dir"/eld*; do
        [ -f "$_eld" ] || continue
        if grep -Eq 'monitor_present[[:space:]]+1([[:space:]]|$)' "$_eld" 2>/dev/null \
            && grep -Eq 'eld_valid[[:space:]]+1([[:space:]]|$)' "$_eld" 2>/dev/null; then
            return 0
        fi
    done
    return 1
}

# Echo the ALSA card id (e.g. "vc4hdmi1") that "default" should map to, or
# nothing if no remap is needed/possible. Pure read of ASOUND_PROC_DIR — the
# unit-testable core.
#
# Returns empty (no action) when: ALSA is absent, a card 0 already exists (stock
# "default" works), or no playback-capable card is found. Otherwise prefers a
# card with a connected HDMI sink, falling back to the lowest-indexed playback
# card.
alsa_pick_default_card() {
    [ -d "$ASOUND_PROC_DIR" ] || return 0
    # Card 0 present → stock "default" (hw:0) is fine, leave it alone.
    [ -d "$ASOUND_PROC_DIR/card0" ] && return 0

    _fallback=""
    _chosen=""
    for _d in "$ASOUND_PROC_DIR"/card[0-9]*; do
        [ -d "$_d" ] || continue

        # Must expose a playback PCM (pcm*p).
        _has_play=""
        for _p in "$_d"/pcm*p; do
            [ -e "$_p" ] && { _has_play=1; break; }
        done
        [ -n "$_has_play" ] || continue

        _id=$(cat "$_d/id" 2>/dev/null) || _id=""
        [ -n "$_id" ] || continue

        [ -z "$_fallback" ] && _fallback="$_id"

        if _alsa_card_sink_connected "$_d"; then
            _chosen="$_id"
            break
        fi
    done

    [ -z "$_chosen" ] && _chosen="$_fallback"
    [ -n "$_chosen" ] && printf '%s\n' "$_chosen"
    return 0
}

# Emit the /etc/asound.conf body that routes "default" to card id $1.
# Pure (stdout only) so tests can assert the content.
alsa_asound_conf_body() {
    _card="$1"
    cat <<EOF
# Auto-generated by the HelixScreen installer.
#
# This board has no ALSA card 0, so the stock "default" device (hw:0) cannot be
# opened. Route "default" to the detected output ("$_card") so UI sounds — and
# anything else that opens "default" (aplay, speaker-test) — work.
#
# Delete this file to restore ALSA's stock behavior. The installer will not
# recreate it if you remove it or hand-edit it.
pcm.!default {
    type plug
    slave.pcm {
        type hw
        card "$_card"
        device 0
    }
}
ctl.!default {
    type hw
    card "$_card"
}
EOF
}

# Top-level install step: configure ALSA "default" if needed. Safe no-op on
# boards where "default" already works, where ALSA is absent, or where the user
# already owns /etc/asound.conf.
configure_alsa_default() {
    if [ -e "$ASOUND_CONF" ]; then
        log_info "ALSA: $ASOUND_CONF already exists — leaving audio config untouched"
        return 0
    fi

    _card=$(alsa_pick_default_card)
    if [ -z "$_card" ]; then
        # Either card 0 exists (default works), no ALSA, or no usable output.
        return 0
    fi

    log_info "ALSA: no card 0; routing \"default\" → card \"$_card\" via $ASOUND_CONF"
    if alsa_asound_conf_body "$_card" | $SUDO tee "$ASOUND_CONF" >/dev/null 2>&1; then
        log_info "ALSA: wrote $ASOUND_CONF (UI sound enabled for HDMI-audio screens)"
    else
        log_warn "ALSA: failed to write $ASOUND_CONF — UI sound may be unavailable"
    fi
    return 0
}
